import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRight, BadgeCheck, Building2, ChevronDown, PackageSearch, RotateCcw, Search, SlidersHorizontal, Store } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import type { CatalogPayload, Product } from "../data/catalog";
import { fetchSectorCatalog, productHasSectorOffer, sectorStores } from "../data/sectorCatalog";
import { getMarketplaceSector, marketplaceSectors, type MarketplaceSectorId } from "./MarketplaceSectors";
import { resolveProductImage } from "../data/productImageResolver";
import { AppDock, PublicHeader } from "./ReferenceExperience";
import "./SearchDiscovery2026.css";

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR").trim();
type SortMode="relevance"|"lowest"|"highest"|"name"|"stores";
function score(product:Product,raw:string){const q=normalize(raw);if(!q)return 20;const name=normalize(product.name);const brand=normalize(product.brand||"");const category=normalize(product.category||"");const establishment=normalize(product.establishment||"");const neighborhood=normalize(product.neighborhood||"");if(name===q)return 0;if(name.startsWith(q))return 1;if(name.includes(q))return 2;if(establishment===q)return 3;if(establishment.includes(q))return 4;if(brand.includes(q))return 5;if(category.includes(q))return 6;if(neighborhood.includes(q))return 7;const words=q.split(/\s+/).filter(Boolean);const haystack=`${name} ${brand} ${category} ${establishment} ${neighborhood}`;return words.every(word=>haystack.includes(word))?8:99}
function ProductThumb({product}:{product:Product}){const src=resolveProductImage(product);return src?<img src={src} alt={product.name} width="76" height="70" loading="lazy"/>:<PackageSearch/>}

export function SearchDiscovery2026(){
 const[params,setParams]=useSearchParams();
 const initialQuery=params.get("q")||"";
 const[catalog,setCatalog]=useState<CatalogPayload|null>(null),[loading,setLoading]=useState(true);
 const[query,setQuery]=useState(initialQuery),[appliedQuery,setAppliedQuery]=useState(initialQuery);
 const[sector,setSector]=useState<MarketplaceSectorId>((getMarketplaceSector(params.get("setor"))?.id||"all") as MarketplaceSectorId);
 const[store,setStore]=useState(params.get("loja")||"all"),[category,setCategory]=useState(params.get("categoria")||"all"),[neighborhood,setNeighborhood]=useState(params.get("bairro")||"all");
 const[minPrice,setMinPrice]=useState(params.get("min")||""),[maxPrice,setMaxPrice]=useState(params.get("max")||"");
 const[sort,setSort]=useState<SortMode>((params.get("ordem") as SortMode)||"relevance"),[filtersOpen,setFiltersOpen]=useState(false),[visible,setVisible]=useState(8);
 useEffect(()=>{let active=true;void fetchSectorCatalog().then(data=>{if(active)setCatalog(data)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const activeSector=getMarketplaceSector(sector);
 const stores=useMemo(()=>{if(!catalog)return[];if(!activeSector)return[...catalog.stores].filter(s=>(s.products||0)>0).sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"));return sectorStores(catalog,activeSector).map(item=>item.store)},[catalog,activeSector]);
 const categories=useMemo(()=>{if(!catalog)return[];const source=activeSector?catalog.products.filter(p=>productHasSectorOffer(p,catalog,activeSector)):catalog.products;return Array.from(new Set(source.map(p=>p.category).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"pt-BR"))},[catalog,activeSector]);
 const neighborhoods=useMemo(()=>Array.from(new Set(stores.map(s=>s.neighborhood).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"pt-BR")),[stores]);
 const activeFilters=[sector!=="all",store!=="all",category!=="all",neighborhood!=="all",Boolean(minPrice),Boolean(maxPrice)].filter(Boolean).length;
 const hasRequest=Boolean(appliedQuery.trim())||activeFilters>0;
 const results=useMemo(()=>{if(!catalog||!hasRequest)return[];const min=Number(minPrice.replace(",",".")),max=Number(maxPrice.replace(",","."));const rows=catalog.products.map(product=>({product,score:score(product,appliedQuery)})).filter(({product,score:rank})=>{if(appliedQuery.trim()&&rank===99)return false;if(activeSector&&!productHasSectorOffer(product,catalog,activeSector))return false;if(store!=="all"&&String(product.establishmentId)!==store&&!product.offers?.some(o=>String(o.establishmentId)===store))return false;if(category!=="all"&&product.category!==category)return false;if(neighborhood!=="all"&&normalize(product.neighborhood)!==normalize(neighborhood)&&!product.offers?.some(o=>normalize(o.neighborhood)===normalize(neighborhood)))return false;if(Number.isFinite(min)&&min>0&&product.minPrice<min)return false;if(Number.isFinite(max)&&max>0&&product.minPrice>max)return false;return true});rows.sort((a,b)=>sort==="lowest"?a.product.minPrice-b.product.minPrice:sort==="highest"?b.product.minPrice-a.product.minPrice:sort==="name"?a.product.name.localeCompare(b.product.name,"pt-BR"):sort==="stores"?(b.product.storeCount||0)-(a.product.storeCount||0):a.score-b.score||a.product.minPrice-b.product.minPrice);return rows.map(r=>r.product)},[catalog,hasRequest,appliedQuery,activeSector,store,category,neighborhood,minPrice,maxPrice,sort]);
 useEffect(()=>setVisible(8),[appliedQuery,sector,store,category,neighborhood,minPrice,maxPrice,sort]);
 useEffect(()=>{if(store!=="all"&&!stores.some(s=>String(s.id)===store))setStore("all")},[stores,store]);
 useEffect(()=>{if(category!=="all"&&!categories.includes(category))setCategory("all")},[categories,category]);
 useEffect(()=>{if(neighborhood!=="all"&&!neighborhoods.includes(neighborhood))setNeighborhood("all")},[neighborhoods,neighborhood]);
 const syncUrl=(nextQuery=appliedQuery)=>{const next:Record<string,string>={};if(nextQuery.trim())next.q=nextQuery.trim();if(sector!=="all")next.setor=sector;if(store!=="all")next.loja=store;if(category!=="all")next.categoria=category;if(neighborhood!=="all")next.bairro=neighborhood;if(minPrice)next.min=minPrice;if(maxPrice)next.max=maxPrice;if(sort!=="relevance")next.ordem=sort;setParams(next,{replace:true})};
 const submit=(e:FormEvent)=>{e.preventDefault();const next=query.trim();setAppliedQuery(next);setVisible(8);syncUrl(next)};
 const applyFilters=()=>{setAppliedQuery(query.trim());setVisible(8);syncUrl(query.trim());setFiltersOpen(false)};
 const reset=()=>{setQuery("");setAppliedQuery("");setSector("all");setStore("all");setCategory("all");setNeighborhood("all");setMinPrice("");setMaxPrice("");setSort("relevance");setVisible(8);setParams({}, {replace:true})};
 return <div className="search26-page"><PublicHeader current="search" /><main id="conteudo-principal" className="search26-shell search26-main">
 <section className="search26-hero"><div><span><Search/> BUSCA INTELIGENTE LOCAL</span><h1>Procure só o que você precisa.</h1><p>Digite um produto, marca, categoria ou estabelecimento. A busca só mostra resultados depois do seu pedido, sem despejar todo o catálogo na tela.</p></div><aside><BadgeCheck/><strong>{catalog?.metrics.products||0} produtos</strong><small>disponíveis para consulta</small></aside></section>
 <form className="search26-search" onSubmit={submit}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: arroz, café, Mercado X…"/><button className="pc-btn pc-btn--primary" disabled={!query.trim()&&activeFilters===0}>Buscar <ArrowRight/></button></form>
 <section className="search26-filterbar"><button type="button" className={filtersOpen||activeFilters?"is-active":""} onClick={()=>setFiltersOpen(v=>!v)}><SlidersHorizontal/>Filtrar busca{activeFilters>0&&<b>{activeFilters}</b>}<ChevronDown/></button>{hasRequest&&<div className="search26-quick"><label><Store/><select value={store} onChange={e=>setStore(e.target.value)}><option value="all">Todos os estabelecimentos</option>{stores.map(s=><option key={s.id} value={String(s.id)}>{s.name}</option>)}</select></label><label><select value={sort} onChange={e=>setSort(e.target.value as SortMode)}><option value="relevance">Mais relevantes</option><option value="lowest">Menor preço</option><option value="highest">Maior preço</option><option value="stores">Mais lojas</option><option value="name">Nome A–Z</option></select></label></div>}{hasRequest&&<button type="button" className="search26-reset" onClick={reset}><RotateCcw/>Nova busca</button>}</section>
 {filtersOpen&&<section className="search26-advanced"><div><label>Estabelecimento<select value={store} onChange={e=>setStore(e.target.value)}><option value="all">Todos</option>{stores.map(s=><option key={s.id} value={String(s.id)}>{s.name}</option>)}</select></label><label>Setor<select value={sector} onChange={e=>setSector(e.target.value as MarketplaceSectorId)}><option value="all">Todos os setores</option>{marketplaceSectors.map(s=><option key={s.id} value={s.id}>{s.shortLabel}</option>)}</select></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Bairro<select value={neighborhood} onChange={e=>setNeighborhood(e.target.value)}><option value="all">Todos</option>{neighborhoods.map(n=><option key={n}>{n}</option>)}</select></label><label>Preço mínimo<input inputMode="decimal" value={minPrice} onChange={e=>setMinPrice(e.target.value)} placeholder="R$ 0,00"/></label><label>Preço máximo<input inputMode="decimal" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="Sem limite"/></label></div><footer><span><Building2/>Mostramos apenas opções realmente cadastradas.</span><button type="button" onClick={applyFilters}>Aplicar e ver resultados</button></footer></section>}
 {!hasRequest?<section className="search26-start"><div className="search26-start-icon"><PackageSearch/></div><div><small>BUSCA SOB DEMANDA</small><h2>O catálogo fica quieto até você pedir.</h2><p>Pesquise pelo nome do produto ou abra os filtros para procurar por estabelecimento, setor, categoria, bairro ou preço.</p></div><div className="search26-suggestions"><button onClick={()=>{setQuery("arroz");setAppliedQuery("arroz")}}>Arroz</button><button onClick={()=>{setQuery("café");setAppliedQuery("café")}}>Café</button><button onClick={()=>setFiltersOpen(true)}>Escolher estabelecimento</button></div></section>:
 <section className="search26-results"><header><div><span>RESULTADOS DA SUA BUSCA</span><h2>{loading?"Consultando catálogo…":`${results.length} ${results.length===1?"resultado":"resultados"}`}</h2></div><small>Mostrando {Math.min(visible,results.length)} por vez</small></header>{!loading&&results.length>0?<div className="search26-grid">{results.slice(0,visible).map(product=><Link to={`/produto/${product.slug||product.id}`} className="search26-card ref-catalog-card" key={product.id}><div className="search26-thumb"><ProductThumb product={product}/></div><div className="search26-copy"><small>{product.category} · {product.brand}</small><strong>{product.name}</strong><span><Store/>{product.establishment}<em>{product.neighborhood}</em></span></div><div className="search26-price"><small>menor preço</small><strong>{brl.format(product.minPrice)}</strong><em>{product.storeCount||product.offers?.length||1} {(product.storeCount||product.offers?.length||1)===1?"loja":"lojas"}</em></div><ArrowRight/></Link>)}</div>:!loading&&<div className="search26-empty"><PackageSearch/><h2>Nenhum resultado compatível</h2><p>Tente outro nome ou remova algum filtro.</p><button onClick={reset}>Fazer nova busca</button></div>}{visible<results.length&&<button className="search26-more" onClick={()=>setVisible(v=>Math.min(v+8,results.length))}>Mostrar mais 8 resultados <span>{results.length-visible} restantes</span></button>}</section>}
 </main><AppDock current="search" /></div>}
